/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#dde4e5",
        "on-secondary": "#381385",
        "inverse-primary": "#006877",
        "surface-container-lowest": "#090f11",
        "on-primary": "#00363e",
        "tertiary": "#ffd6a3",
        "on-secondary-container": "#bea8ff",
        "primary": "#8aebff",
        "on-surface": "#dde4e5",
        "on-secondary-fixed": "#21005e",
        "on-primary-fixed": "#001f25",
        "tertiary-fixed": "#ffddb5",
        "primary-fixed-dim": "#2fd9f4",
        "surface-container": "#1a2122",
        "surface-container-highest": "#2f3638",
        "surface-tint": "#2fd9f4",
        "surface-dim": "#0e1416",
        "surface-variant": "#2f3638",
        "secondary-fixed-dim": "#cebdff",
        "tertiary-fixed-dim": "#ffb957",
        "tertiary-container": "#ffb13b",
        "outline": "#859397",
        "on-tertiary": "#462b00",
        "inverse-on-surface": "#2b3233",
        "on-tertiary-container": "#6e4600",
        "on-tertiary-fixed-variant": "#643f00",
        "surface-container-low": "#161d1e",
        "background": "#0e1416",
        "on-background": "#dde4e5",
        "secondary": "#cebdff",
        "primary-container": "#22d3ee",
        "surface-container-high": "#242b2d",
        "on-tertiary-fixed": "#2a1800",
        "on-surface-variant": "#bbc9cd",
        "on-error": "#690005",
        "primary-fixed": "#a2eeff",
        "surface-bright": "#343a3c",
        "error-container": "#93000a",
        "secondary-fixed": "#e8ddff",
        "secondary-container": "#4f319c",
        "on-primary-fixed-variant": "#004e5a",
        "outline-variant": "#3c494c",
        "on-error-container": "#ffdad6",
        "surface": "#0e1416",
        "error": "#ffb4ab",
        "on-secondary-fixed-variant": "#4f319c",
        "on-primary-container": "#005763"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "container-max": "1440px",
        "xxl": "64px",
        "sm": "8px",
        "md": "16px",
        "xs": "4px",
        "xl": "40px",
        "lg": "24px",
        "unit": "4px"
      },
      fontFamily: {
        "label-caps": ["Inter"],
        "body-sm": ["Inter"],
        "h2": ["Space Grotesk"],
        "body-md": ["Inter"],
        "display-lg": ["Space Grotesk"],
        "body-lg": ["Inter"],
        "h1": ["Space Grotesk"],
        "h3": ["Space Grotesk"],
        "data-mono": ["Space Grotesk"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "h2": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "h1": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "h3": ["20px", { lineHeight: "1.4", fontWeight: "500" }],
        "data-mono": ["16px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
